layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    
  - name: API
    web_url: https://github.com/topics/api
    image_url: https://cdn3.iconfinder.com/data/icons/service-design-tools/100/3_Mar-20-512.png

  - name: Healthcare
    web_url: https://github.com/topics/healthcare
    image_url: https://africawatersolutions.org/wp-content/uploads/2018/09/icon-healthcare.png

